Feat[TE-15569]: Addon to access downloaded PDF files on the cloud and extract the content
testsigmahq/testsigma-addons pull request #40
Opened 2024-01-10 11:53 UTC by SunilGembali

2024-01-10 11:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/testsigmahq/testsigma-addons?pullRequest=40) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/testsigmahq/testsigma-addons?pullRequest=40) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/testsigmahq/testsigma-addons?pullRequest=40) it.</sub>

2024-01-10 12:34 UTC, rajesh-testsigma commented on pdfdataextractor/src/main/java/com/testsigma/addons/web/util/PdfAndDocUtilities.java
> +        driver.switchTo().window(currentWindowHandle);
Move this to finally, this is mandatory switch

2024-01-10 13:49 UTC, SunilGembali commented on pdfdataextractor/src/main/java/com/testsigma/addons/web/util/PdfAndDocUtilities.java
> +        driver.switchTo().window(currentWindowHandle);
Moved to finally block.

2024-01-11 03:55 UTC, ManoharKrishnaBoppe requested changes
Please do update the kibbutz bootstrap.

2024-01-23 13:43 UTC, SunilGembali commented
> Please do update the kibbutz bootstrap.

I made the changes and raised the PR for testsigma-kibbutz

2024-02-05 11:36 UTC, rajesh-testsigma approved these changes

2024-02-05 11:37 UTC, merged