Feat[TE-15256]: Image based Actions addon
testsigmahq/testsigma-addons pull request #41
Opened 2024-02-05 06:55 UTC by SunilGembali

2024-02-05 06:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/testsigmahq/testsigma-addons?pullRequest=41) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/testsigmahq/testsigma-addons?pullRequest=41) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/testsigmahq/testsigma-addons?pullRequest=41) it.</sub>

2024-02-06 09:51 UTC, rajesh-testsigma approved these changes

2024-02-23 11:52 UTC, ManoharKrishnaBoppe requested changes
@SunilGembali Can you please move out the common code and reuse ?

2024-02-23 12:32 UTC, SunilGembali commented
> @SunilGembali Can you please move out the common code and reuse ?

The code was done in many phases and by several people. So now to add reusabililty to this addon takes more time.

2024-02-23 19:21 UTC, merged