feat[TE-17324] Addon for sending reply mails
testsigmahq/testsigma-addons pull request #52
Opened 2024-03-19 13:29 UTC by navyana-srivalli

2024-03-19 13:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/testsigmahq/testsigma-addons?pullRequest=52) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/testsigmahq/testsigma-addons?pullRequest=52) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/testsigmahq/testsigma-addons?pullRequest=52) it.</sub>

2024-03-19 14:07 UTC, PratheepV requested changes

2024-03-19 14:07 UTC, PratheepV commented on reply_mails/src/main/resources/testsigma-sdk.properties
> +testsigma-sdk.api.key=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZWYtZHNzZndlc2xkbGY0aTg4c2pkZmoiLCJ1bmlxdWVJZCI6IjE3IiwiZXh0ZXJuYWxUZW5hbnRJZCI6IjEifQ.lmcMsU7DUbHCc-9H28o7qIX3XCYixGYNaIKlxzi-jIznhcsqFI5jAkzwo
@navyana-srivalli do we need this?

2024-03-20 07:24 UTC, navyana-srivalli commented on reply_mails/src/main/resources/testsigma-sdk.properties
> +testsigma-sdk.api.key=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZWYtZHNzZndlc2xkbGY0aTg4c2pkZmoiLCJ1bmlxdWVJZCI6IjE3IiwiZXh0ZXJuYWxUZW5hbnRJZCI6IjEifQ.lmcMsU7DUbHCc-9H28o7qIX3XCYixGYNaIKlxzi-jIznhcsqFI5jAkzwo
Yes

2024-04-02 14:41 UTC, ManoharKrishnaBoppe approved these changes

2024-04-02 14:41 UTC, merged